x86_64-w64-mingw32-gcc -O2 -fPIC -I ../ext/spng/ -I ../include/ -I ../sdl/ -I ../ext/ -I ../ext/libadlmidi/include/\
    ../src/ssi/ssi-scmd.c \
    ../src/ssi/ds-load-save.c \
    ../src/ssi/ssi-item.c \
    ../src/region.c \
    ../src/combat.c \
    ../src/powers/effect.c \
    ../src/powers/wizard.c \
    ../src/powers/wizard/psionic-dampener.c \
    ../src/powers/wizard/incendiary-cloud.c \
    ../src/powers/wizard/power-word-blind.c \
    ../src/powers/wizard/wall-of-ice.c \
    ../src/powers/wizard/shocking-grasp.c \
    ../src/powers/wizard/wall-of-ash.c \
    ../src/powers/wizard/spirit-armor.c \
    ../src/powers/wizard/control-undead.c \
    ../src/powers/wizard/fog-cloud.c \
    ../src/powers/wizard/minute-meteors.c \
    ../src/powers/wizard/monster-summoning-vii.c \
    ../src/powers/wizard/chain-lightning.c \
    ../src/powers/wizard/hold-monster.c \
    ../src/powers/wizard/improved-invisibility.c \
    ../src/powers/wizard/monster-summoning-i.c \
    ../src/powers/wizard/power-word-stun.c \
    ../src/powers/wizard/conjure-greater-elemental.c \
    ../src/powers/wizard/bigbys-clenched-fist.c \
    ../src/powers/wizard/mordenkainens-disjunction.c \
    ../src/powers/wizard/feeble-mind.c \
    ../src/powers/wizard/charm-person.c \
    ../src/powers/wizard/monster-summoning-ii.c \
    ../src/powers/wizard/dominate.c \
    ../src/powers/wizard/vampiric-touch.c \
    ../src/powers/wizard/mass-charm.c \
    ../src/powers/wizard/stone-to-flesh.c \
    ../src/powers/wizard/monster-summoning-vi.c \
    ../src/powers/wizard/shield.c \
    ../src/powers/wizard/solid-fog.c \
    ../src/powers/wizard/improved-slow.c \
    ../src/powers/wizard/grease.c \
    ../src/powers/wizard/mass-invisibility.c \
    ../src/powers/wizard/m-globe-of-invulnerability.c \
    ../src/powers/wizard/hold-undead.c \
    ../src/powers/wizard/wall-of-fog.c \
    ../src/powers/wizard/slow.c \
    ../src/powers/wizard/death-spell.c \
    ../src/powers/wizard/globe-of-invulnerability.c \
    ../src/powers/wizard/death-fog.c \
    ../src/powers/wizard/prismatic-sphere.c \
    ../src/powers/wizard/spell-turning.c \
    ../src/powers/wizard/level-drain.c \
    ../src/powers/wizard/fear.c \
    ../src/powers/wizard/time-stop.c \
    ../src/powers/wizard/ice-storm.c \
    ../src/powers/wizard/evards-black-tentacles.c \
    ../src/powers/wizard/ottos-irresistible-dance.c \
    ../src/powers/wizard/monster-summoning-iii.c \
    ../src/powers/wizard/otilukes-telekinetic-sphere.c \
    ../src/powers/wizard/reincarnation.c \
    ../src/powers/wizard/invisibility.c \
    ../src/powers/wizard/web.c \
    ../src/powers/wizard/scare.c \
    ../src/powers/wizard/cloud-kill.c \
    ../src/powers/wizard/cone-of-cold.c \
    ../src/powers/wizard/mind-blank-wizard.c \
    ../src/powers/wizard/stinking-cloud.c \
    ../src/powers/wizard/dispel-magic.c \
    ../src/powers/wizard/anti-magic-shell.c \
    ../src/powers/wizard/otilukes-resilient-sphere.c \
    ../src/powers/wizard/hold-person.c \
    ../src/powers/wizard/flesh-to-stone.c \
    ../src/powers/wizard/mordenkainens-sword.c \
    ../src/powers/wizard/conjure-elemental.c \
    ../src/powers/wizard/wall-of-fire.c \
    ../src/powers/wizard/spider-strand.c \
    ../src/powers/wizard/delayed-blast-fireball.c \
    ../src/powers/wizard/fire-shield.c \
    ../src/powers/wizard/rainbow-pattern.c \
    ../src/powers/wizard/meteor-swarm.c \
    ../src/powers/wizard/minor-spell-turning.c \
    ../src/powers/wizard/armor.c \
    ../src/powers/wizard/mirror-image.c \
    ../src/powers/wizard/acid-arrow.c \
    ../src/powers/wizard/chill-touch.c \
    ../src/powers/wizard/color-spray.c \
    ../src/powers/wizard/blur.c \
    ../src/powers/wizard/monster-summoning-iv.c \
    ../src/powers/wizard/force-cage.c \
    ../src/powers/wizard/dismissal.c \
    ../src/powers/wizard/bigbys-crushing-hand.c \
    ../src/powers/wizard/improved-haste.c \
    ../src/powers/wizard/pebble-to-boulder.c \
    ../src/powers/wizard/dome-of-invulnerability.c \
    ../src/powers/wizard/haste.c \
    ../src/powers/wizard/protection-from-missiles.c \
    ../src/powers/wizard/lightning-bolt.c \
    ../src/powers/wizard/enlarge.c \
    ../src/powers/wizard/crystal-brittle.c \
    ../src/powers/wizard/spell-immunity.c \
    ../src/powers/wizard/flaming-sphere.c \
    ../src/powers/wizard/confusion.c \
    ../src/powers/wizard/magical-plague.c \
    ../src/powers/wizard/blink.c \
    ../src/powers/wizard/tensers-transformation.c \
    ../src/powers/wizard/prismatic-wall.c \
    ../src/powers/wizard/wall-of-force.c \
    ../src/powers/wizard/wall-of-stone.c \
    ../src/powers/wizard/charm-monster.c \
    ../src/powers/wizard/disintegrate.c \
    ../src/powers/wizard/detect-invisible.c \
    ../src/powers/wizard/monster-summoning-v.c \
    ../src/powers/wizard/power-word-kill.c \
    ../src/powers/wizard/fireball.c \
    ../src/powers/wizard/protection-from-paralysis.c \
    ../src/powers/wizard/rift.c \
    ../src/powers/wizard/prismatic-spray.c \
    ../src/powers/wizard/stone-skin.c \
    ../src/powers/wizard/burning-hands.c \
    ../src/powers/wizard/glitter-dust.c \
    ../src/powers/wizard/gaze-reflection.c \
    ../src/powers/wizard/chaos.c \
    ../src/powers/wizard/flaming-arrow.c \
    ../src/powers/wizard/strength.c \
    ../src/powers/wizard/minor-malison.c \
    ../src/powers/wizard/finger-of-death.c \
    ../src/powers/wizard/summon-shadow.c \
    ../src/powers/wizard/magic-missile.c \
    ../src/powers/wizard/lower-resistance-to-magic.c \
    ../src/powers/powers.c \
    ../src/powers/powers-generator.c \
    ../src/settings.c \
    ../src/arbiter.c \
    ../src/systems/alignment.c \
    ../src/systems/race.c \
    ../src/systems/class.c \
    ../src/systems/stats.c \
    ../src/trigger.c \
    ../src/gff/gff-image.c \
    ../src/gff/gff-xmi.c \
    ../src/gff/gff-char.c \
    ../src/gff/gff.c \
    ../src/gff/gff-map.c \
    ../src/objects/item.c \
    ../src/objects/player.c \
    ../src/objects/entity-list.c \
    ../src/objects/entity.c \
    ../src/objects/entity-animation.c \
    ../src/strdup.c \
    ../src/ui/combat-status.c \
    ../src/ui/sol_textbox.c \
    ../src/ui/inventory.c \
    ../src/ui/add-load-save.c \
    ../src/ui/popup.c \
    ../src/ui/portrait.c \
    ../src/ui/view-character.c \
    ../src/ui/animation.c \
    ../src/ui/interact.c \
    ../src/ui/new-character.c \
    ../src/ui/label.c \
    ../src/ui/window-manager.c \
    ../src/ui/map.c \
    ../src/ui/window-main.c \
    ../src/ui/narrate.c \
    ../src/ui/game-menu.c \
    ../src/ui/description.c \
    ../src/combat-region.c \
    ../src/lua/region.c \
    ../src/lua/settings.c \
    ../src/lua/ds.c \
    ../src/lua/manager.c \
    ../src/lua/entity.c \
    ../src/lua/lua-structs.c \
    ../src/rules.c \
    ../src/replay.c \
    ../src/gpl/gpl-lua.c \
    ../src/gpl/gpl-request.c \
    ../src/gpl/state.c \
    ../src/gpl/gpl-string.c \
    ../src/gpl/gpl-manager.c \
    ../src/gpl/gpl.c \
    ../src/gpl/gpl-var.c \
    ../src/support.c \
    ../src/gameloop.c \
    ../src/input.c \
    ../src/region-manager.c \
    ../sdl/main.c \
    ../sdl/browse.c \
    ../sdl/textbox.c \
    ../sdl/utils.c \
    ../sdl/mouse.c \
    ../sdl/save-load.c \
    ../sdl/background.c \
    ../sdl/sprite.c \
    ../sdl/lua-generate-globals.c \
    ../sdl/font.c \
    ../sdl/window.c \
    ../sdl/audio.c \
    ../ext/xmi2mid.c \
    ../ext/spng/spng.c \
    -lmingw32 -lsndfile -llua53 -lSDL2main -lSDL2 -lSDL2_ttf -lADLMIDI -lz
