// This file is generated.
#include <stdlib.h>
#include "powers.h"
#include "wizard.h"

extern void wizard_armor_setup(power_t *p);
extern void wizard_burning_hands_setup(power_t *p);
extern void wizard_charm_person_setup(power_t *p);
extern void wizard_chill_touch_setup(power_t *p);
extern void wizard_color_spray_setup(power_t *p);
extern void wizard_enlarge_setup(power_t *p);
extern void wizard_gaze_reflection_setup(power_t *p);
extern void wizard_grease_setup(power_t *p);
extern void wizard_magic_missile_setup(power_t *p);
extern void wizard_shield_setup(power_t *p);
extern void wizard_shocking_grasp_setup(power_t *p);
extern void wizard_wall_of_fog_setup(power_t *p);

extern void wizard_blur_setup(power_t *p);
extern void wizard_detect_invisible_setup(power_t *p);
extern void wizard_flaming_sphere_setup(power_t *p);
extern void wizard_fog_cloud_setup(power_t *p);
extern void wizard_glitter_dust_setup(power_t *p);
extern void wizard_invisibility_setup(power_t *p);
extern void wizard_acid_arrow_setup(power_t *p);
extern void wizard_mirror_image_setup(power_t *p);
extern void wizard_protection_from_paralysis_setup(power_t *p);
extern void wizard_scare_setup(power_t *p);
extern void wizard_stinking_cloud_setup(power_t *p);
extern void wizard_strength_setup(power_t *p);
extern void wizard_web_setup(power_t *p);

extern void wizard_blink_setup(power_t *p);
extern void wizard_dispel_magic_setup(power_t *p);
extern void wizard_fireball_setup(power_t *p);
extern void wizard_flaming_arrow_setup(power_t *p);
extern void wizard_haste_setup(power_t *p);
extern void wizard_hold_person_setup(power_t *p);
extern void wizard_hold_undead_setup(power_t *p);
extern void wizard_lightning_bolt_setup(power_t *p);
extern void wizard_minute_meteors_setup(power_t *p);
extern void wizard_minor_malison_setup(power_t *p);
extern void wizard_protection_from_missiles_setup(power_t *p);
extern void wizard_slow_setup(power_t *p);
extern void wizard_spirit_armor_setup(power_t *p);
extern void wizard_vampiric_touch_setup(power_t *p);
extern void wizard_monster_summoning_i_setup(power_t *p);

extern void wizard_charm_monster_setup(power_t *p);
extern void wizard_confusion_setup(power_t *p);
extern void wizard_fear_setup(power_t *p);
extern void wizard_fire_shield_setup(power_t *p);
extern void wizard_ice_storm_setup(power_t *p);
extern void wizard_improved_invisibility_setup(power_t *p);
extern void wizard_m_globe_of_invulnerability_setup(power_t *p);
extern void wizard_minor_spell_turning_setup(power_t *p);
extern void wizard_otilukes_resilient_sphere_setup(power_t *p);
extern void wizard_psionic_dampener_setup(power_t *p);
extern void wizard_rainbow_pattern_setup(power_t *p);
extern void wizard_solid_fog_setup(power_t *p);
extern void wizard_spider_strand_setup(power_t *p);
extern void wizard_stone_skin_setup(power_t *p);
extern void wizard_pebble_to_boulder_setup(power_t *p);
extern void wizard_wall_of_fire_setup(power_t *p);
extern void wizard_wall_of_ice_setup(power_t *p);
extern void wizard_monster_summoning_ii_setup(power_t *p);
extern void wizard_evards_black_tentacles_setup(power_t *p);

extern void wizard_chaos_setup(power_t *p);
extern void wizard_cloud_kill_setup(power_t *p);
extern void wizard_cone_of_cold_setup(power_t *p);
extern void wizard_conjure_elemental_setup(power_t *p);
extern void wizard_dismissal_setup(power_t *p);
extern void wizard_dominate_setup(power_t *p);
extern void wizard_feeble_mind_setup(power_t *p);
extern void wizard_hold_monster_setup(power_t *p);
extern void wizard_lower_resistance_to_magic_setup(power_t *p);
extern void wizard_summon_shadow_setup(power_t *p);
extern void wizard_wall_of_force_setup(power_t *p);
extern void wizard_wall_of_stone_setup(power_t *p);
extern void wizard_monster_summoning_iii_setup(power_t *p);

extern void wizard_anti_magic_shell_setup(power_t *p);
extern void wizard_chain_lightning_setup(power_t *p);
extern void wizard_death_fog_setup(power_t *p);
extern void wizard_death_spell_setup(power_t *p);
extern void wizard_disintegrate_setup(power_t *p);
extern void wizard_globe_of_invulnerability_setup(power_t *p);
extern void wizard_improved_haste_setup(power_t *p);
extern void wizard_improved_slow_setup(power_t *p);
extern void wizard_monster_summoning_iv_setup(power_t *p);
extern void wizard_reincarnation_setup(power_t *p);
extern void wizard_stone_to_flesh_setup(power_t *p);
extern void wizard_flesh_to_stone_setup(power_t *p);
extern void wizard_tensers_transformation_setup(power_t *p);

extern void wizard_conjure_greater_elemental_setup(power_t *p);
extern void wizard_control_undead_setup(power_t *p);
extern void wizard_delayed_blast_fireball_setup(power_t *p);
extern void wizard_finger_of_death_setup(power_t *p);
extern void wizard_force_cage_setup(power_t *p);
extern void wizard_mass_invisibility_setup(power_t *p);
extern void wizard_monster_summoning_v_setup(power_t *p);
extern void wizard_mordenkainens_sword_setup(power_t *p);
extern void wizard_power_word_stun_setup(power_t *p);
extern void wizard_prismatic_spray_setup(power_t *p);
extern void wizard_spell_turning_setup(power_t *p);

extern void wizard_bigbys_clenched_fist_setup(power_t *p);
extern void wizard_incendiary_cloud_setup(power_t *p);
extern void wizard_mass_charm_setup(power_t *p);
extern void wizard_mind_blank_wizard_setup(power_t *p);
extern void wizard_monster_summoning_vi_setup(power_t *p);
extern void wizard_otilukes_telekinetic_sphere_setup(power_t *p);
extern void wizard_ottos_irresistible_dance_setup(power_t *p);
extern void wizard_power_word_blind_setup(power_t *p);
extern void wizard_prismatic_wall_setup(power_t *p);
extern void wizard_spell_immunity_setup(power_t *p);

extern void wizard_bigbys_crushing_hand_setup(power_t *p);
extern void wizard_crystal_brittle_setup(power_t *p);
extern void wizard_level_drain_setup(power_t *p);
extern void wizard_meteor_swarm_setup(power_t *p);
extern void wizard_monster_summoning_vii_setup(power_t *p);
extern void wizard_mordenkainens_disjunction_setup(power_t *p);
extern void wizard_power_word_kill_setup(power_t *p);
extern void wizard_prismatic_sphere_setup(power_t *p);
extern void wizard_time_stop_setup(power_t *p);

extern void wizard_dome_of_invulnerability_setup(power_t *p);
extern void wizard_magical_plague_setup(power_t *p);
extern void wizard_rift_setup(power_t *p);
extern void wizard_wall_of_ash_setup(power_t *p);


void wizard_setup_powers() {
    power_t *p;
    p = power_create();
    wizard_armor_setup(p);
    wizard_add_power(p, WIZ_ARMOR);
    p = power_create();
    wizard_burning_hands_setup(p);
    wizard_add_power(p, WIZ_BURNING_HANDS);
    p = power_create();
    wizard_charm_person_setup(p);
    wizard_add_power(p, WIZ_CHARM_PERSON);
    p = power_create();
    wizard_chill_touch_setup(p);
    wizard_add_power(p, WIZ_CHILL_TOUCH);
    p = power_create();
    wizard_color_spray_setup(p);
    wizard_add_power(p, WIZ_COLOR_SPRAY);
    p = power_create();
    wizard_enlarge_setup(p);
    wizard_add_power(p, WIZ_ENLARGE);
    p = power_create();
    wizard_gaze_reflection_setup(p);
    wizard_add_power(p, WIZ_GAZE_REFLECTION);
    p = power_create();
    wizard_grease_setup(p);
    wizard_add_power(p, WIZ_GREASE);
    p = power_create();
    wizard_magic_missile_setup(p);
    wizard_add_power(p, WIZ_MAGIC_MISSILE);
    p = power_create();
    wizard_shield_setup(p);
    wizard_add_power(p, WIZ_SHIELD);
    p = power_create();
    wizard_shocking_grasp_setup(p);
    wizard_add_power(p, WIZ_SHOCKING_GRASP);
    p = power_create();
    wizard_wall_of_fog_setup(p);
    wizard_add_power(p, WIZ_WALL_OF_FOG);

    p = power_create();
    wizard_blur_setup(p);
    wizard_add_power(p, WIZ_BLUR);
    p = power_create();
    wizard_detect_invisible_setup(p);
    wizard_add_power(p, WIZ_DETECT_INVISIBLE);
    p = power_create();
    wizard_flaming_sphere_setup(p);
    wizard_add_power(p, WIZ_FLAMING_SPHERE);
    p = power_create();
    wizard_fog_cloud_setup(p);
    wizard_add_power(p, WIZ_FOG_CLOUD);
    p = power_create();
    wizard_glitter_dust_setup(p);
    wizard_add_power(p, WIZ_GLITTER_DUST);
    p = power_create();
    wizard_invisibility_setup(p);
    wizard_add_power(p, WIZ_INVISIBILITY);
    p = power_create();
    wizard_acid_arrow_setup(p);
    wizard_add_power(p, WIZ_ACID_ARROW);
    p = power_create();
    wizard_mirror_image_setup(p);
    wizard_add_power(p, WIZ_MIRROR_IMAGE);
    p = power_create();
    wizard_protection_from_paralysis_setup(p);
    wizard_add_power(p, WIZ_PROTECTION_FROM_PARALYSIS);
    p = power_create();
    wizard_scare_setup(p);
    wizard_add_power(p, WIZ_SCARE);
    p = power_create();
    wizard_stinking_cloud_setup(p);
    wizard_add_power(p, WIZ_STINKING_CLOUD);
    p = power_create();
    wizard_strength_setup(p);
    wizard_add_power(p, WIZ_STRENGTH);
    p = power_create();
    wizard_web_setup(p);
    wizard_add_power(p, WIZ_WEB);

    p = power_create();
    wizard_blink_setup(p);
    wizard_add_power(p, WIZ_BLINK);
    p = power_create();
    wizard_dispel_magic_setup(p);
    wizard_add_power(p, WIZ_DISPEL_MAGIC);
    p = power_create();
    wizard_fireball_setup(p);
    wizard_add_power(p, WIZ_FIREBALL);
    p = power_create();
    wizard_flaming_arrow_setup(p);
    wizard_add_power(p, WIZ_FLAMING_ARROW);
    p = power_create();
    wizard_haste_setup(p);
    wizard_add_power(p, WIZ_HASTE);
    p = power_create();
    wizard_hold_person_setup(p);
    wizard_add_power(p, WIZ_HOLD_PERSON);
    p = power_create();
    wizard_hold_undead_setup(p);
    wizard_add_power(p, WIZ_HOLD_UNDEAD);
    p = power_create();
    wizard_lightning_bolt_setup(p);
    wizard_add_power(p, WIZ_LIGHTNING_BOLT);
    p = power_create();
    wizard_minute_meteors_setup(p);
    wizard_add_power(p, WIZ_MINUTE_METEORS);
    p = power_create();
    wizard_minor_malison_setup(p);
    wizard_add_power(p, WIZ_MINOR_MALISON);
    p = power_create();
    wizard_protection_from_missiles_setup(p);
    wizard_add_power(p, WIZ_PROTECTION_FROM_MISSILES);
    p = power_create();
    wizard_slow_setup(p);
    wizard_add_power(p, WIZ_SLOW);
    p = power_create();
    wizard_spirit_armor_setup(p);
    wizard_add_power(p, WIZ_SPIRIT_ARMOR);
    p = power_create();
    wizard_vampiric_touch_setup(p);
    wizard_add_power(p, WIZ_VAMPIRIC_TOUCH);
    p = power_create();
    wizard_monster_summoning_i_setup(p);
    wizard_add_power(p, WIZ_MONSTER_SUMMONING_I);

    p = power_create();
    wizard_charm_monster_setup(p);
    wizard_add_power(p, WIZ_CHARM_MONSTER);
    p = power_create();
    wizard_confusion_setup(p);
    wizard_add_power(p, WIZ_CONFUSION);
    p = power_create();
    wizard_fear_setup(p);
    wizard_add_power(p, WIZ_FEAR);
    p = power_create();
    wizard_fire_shield_setup(p);
    wizard_add_power(p, WIZ_FIRE_SHIELD);
    p = power_create();
    wizard_ice_storm_setup(p);
    wizard_add_power(p, WIZ_ICE_STORM);
    p = power_create();
    wizard_improved_invisibility_setup(p);
    wizard_add_power(p, WIZ_IMPROVED_INVISIBILITY);
    p = power_create();
    wizard_m_globe_of_invulnerability_setup(p);
    wizard_add_power(p, WIZ_M_GLOBE_OF_INVULNERABILITY);
    p = power_create();
    wizard_minor_spell_turning_setup(p);
    wizard_add_power(p, WIZ_MINOR_SPELL_TURNING);
    p = power_create();
    wizard_otilukes_resilient_sphere_setup(p);
    wizard_add_power(p, WIZ_OTILUKES_RESILIENT_SPHERE);
    p = power_create();
    wizard_psionic_dampener_setup(p);
    wizard_add_power(p, WIZ_PSIONIC_DAMPENER);
    p = power_create();
    wizard_rainbow_pattern_setup(p);
    wizard_add_power(p, WIZ_RAINBOW_PATTERN);
    p = power_create();
    wizard_solid_fog_setup(p);
    wizard_add_power(p, WIZ_SOLID_FOG);
    p = power_create();
    wizard_spider_strand_setup(p);
    wizard_add_power(p, WIZ_SPIDER_STRAND);
    p = power_create();
    wizard_stone_skin_setup(p);
    wizard_add_power(p, WIZ_STONE_SKIN);
    p = power_create();
    wizard_pebble_to_boulder_setup(p);
    wizard_add_power(p, WIZ_PEBBLE_TO_BOULDER);
    p = power_create();
    wizard_wall_of_fire_setup(p);
    wizard_add_power(p, WIZ_WALL_OF_FIRE);
    p = power_create();
    wizard_wall_of_ice_setup(p);
    wizard_add_power(p, WIZ_WALL_OF_ICE);
    p = power_create();
    wizard_monster_summoning_ii_setup(p);
    wizard_add_power(p, WIZ_MONSTER_SUMMONING_II);
    p = power_create();
    wizard_evards_black_tentacles_setup(p);
    wizard_add_power(p, WIZ_EVARDS_BLACK_TENTACLES);

    p = power_create();
    wizard_chaos_setup(p);
    wizard_add_power(p, WIZ_CHAOS);
    p = power_create();
    wizard_cloud_kill_setup(p);
    wizard_add_power(p, WIZ_CLOUD_KILL);
    p = power_create();
    wizard_cone_of_cold_setup(p);
    wizard_add_power(p, WIZ_CONE_OF_COLD);
    p = power_create();
    wizard_conjure_elemental_setup(p);
    wizard_add_power(p, WIZ_CONJURE_ELEMENTAL);
    p = power_create();
    wizard_dismissal_setup(p);
    wizard_add_power(p, WIZ_DISMISSAL);
    p = power_create();
    wizard_dominate_setup(p);
    wizard_add_power(p, WIZ_DOMINATE);
    p = power_create();
    wizard_feeble_mind_setup(p);
    wizard_add_power(p, WIZ_FEEBLE_MIND);
    p = power_create();
    wizard_hold_monster_setup(p);
    wizard_add_power(p, WIZ_HOLD_MONSTER);
    p = power_create();
    wizard_lower_resistance_to_magic_setup(p);
    wizard_add_power(p, WIZ_LOWER_RESISTANCE_TO_MAGIC);
    p = power_create();
    wizard_summon_shadow_setup(p);
    wizard_add_power(p, WIZ_SUMMON_SHADOW);
    p = power_create();
    wizard_wall_of_force_setup(p);
    wizard_add_power(p, WIZ_WALL_OF_FORCE);
    p = power_create();
    wizard_wall_of_stone_setup(p);
    wizard_add_power(p, WIZ_WALL_OF_STONE);
    p = power_create();
    wizard_monster_summoning_iii_setup(p);
    wizard_add_power(p, WIZ_MONSTER_SUMMONING_III);

    p = power_create();
    wizard_anti_magic_shell_setup(p);
    wizard_add_power(p, WIZ_ANTI_MAGIC_SHELL);
    p = power_create();
    wizard_chain_lightning_setup(p);
    wizard_add_power(p, WIZ_CHAIN_LIGHTNING);
    p = power_create();
    wizard_death_fog_setup(p);
    wizard_add_power(p, WIZ_DEATH_FOG);
    p = power_create();
    wizard_death_spell_setup(p);
    wizard_add_power(p, WIZ_DEATH_SPELL);
    p = power_create();
    wizard_disintegrate_setup(p);
    wizard_add_power(p, WIZ_DISINTEGRATE);
    p = power_create();
    wizard_globe_of_invulnerability_setup(p);
    wizard_add_power(p, WIZ_GLOBE_OF_INVULNERABILITY);
    p = power_create();
    wizard_improved_haste_setup(p);
    wizard_add_power(p, WIZ_IMPROVED_HASTE);
    p = power_create();
    wizard_improved_slow_setup(p);
    wizard_add_power(p, WIZ_IMPROVED_SLOW);
    p = power_create();
    wizard_monster_summoning_iv_setup(p);
    wizard_add_power(p, WIZ_MONSTER_SUMMONING_IV);
    p = power_create();
    wizard_reincarnation_setup(p);
    wizard_add_power(p, WIZ_REINCARNATION);
    p = power_create();
    wizard_stone_to_flesh_setup(p);
    wizard_add_power(p, WIZ_STONE_TO_FLESH);
    p = power_create();
    wizard_flesh_to_stone_setup(p);
    wizard_add_power(p, WIZ_FLESH_TO_STONE);
    p = power_create();
    wizard_tensers_transformation_setup(p);
    wizard_add_power(p, WIZ_TENSERS_TRANSFORMATION);

    p = power_create();
    wizard_conjure_greater_elemental_setup(p);
    wizard_add_power(p, WIZ_CONJURE_GREATER_ELEMENTAL);
    p = power_create();
    wizard_control_undead_setup(p);
    wizard_add_power(p, WIZ_CONTROL_UNDEAD);
    p = power_create();
    wizard_delayed_blast_fireball_setup(p);
    wizard_add_power(p, WIZ_DELAYED_BLAST_FIREBALL);
    p = power_create();
    wizard_finger_of_death_setup(p);
    wizard_add_power(p, WIZ_FINGER_OF_DEATH);
    p = power_create();
    wizard_force_cage_setup(p);
    wizard_add_power(p, WIZ_FORCE_CAGE);
    p = power_create();
    wizard_mass_invisibility_setup(p);
    wizard_add_power(p, WIZ_MASS_INVISIBILITY);
    p = power_create();
    wizard_monster_summoning_v_setup(p);
    wizard_add_power(p, WIZ_MONSTER_SUMMONING_V);
    p = power_create();
    wizard_mordenkainens_sword_setup(p);
    wizard_add_power(p, WIZ_MORDENKAINENS_SWORD);
    p = power_create();
    wizard_power_word_stun_setup(p);
    wizard_add_power(p, WIZ_POWER_WORD_STUN);
    p = power_create();
    wizard_prismatic_spray_setup(p);
    wizard_add_power(p, WIZ_PRISMATIC_SPRAY);
    p = power_create();
    wizard_spell_turning_setup(p);
    wizard_add_power(p, WIZ_SPELL_TURNING);

    p = power_create();
    wizard_bigbys_clenched_fist_setup(p);
    wizard_add_power(p, WIZ_BIGBYS_CLENCHED_FIST);
    p = power_create();
    wizard_incendiary_cloud_setup(p);
    wizard_add_power(p, WIZ_INCENDIARY_CLOUD);
    p = power_create();
    wizard_mass_charm_setup(p);
    wizard_add_power(p, WIZ_MASS_CHARM);
    p = power_create();
    wizard_mind_blank_wizard_setup(p);
    wizard_add_power(p, WIZ_MIND_BLANK_WIZARD);
    p = power_create();
    wizard_monster_summoning_vi_setup(p);
    wizard_add_power(p, WIZ_MONSTER_SUMMONING_VI);
    p = power_create();
    wizard_otilukes_telekinetic_sphere_setup(p);
    wizard_add_power(p, WIZ_OTILUKES_TELEKINETIC_SPHERE);
    p = power_create();
    wizard_ottos_irresistible_dance_setup(p);
    wizard_add_power(p, WIZ_OTTOS_IRRESISTIBLE_DANCE);
    p = power_create();
    wizard_power_word_blind_setup(p);
    wizard_add_power(p, WIZ_POWER_WORD_BLIND);
    p = power_create();
    wizard_prismatic_wall_setup(p);
    wizard_add_power(p, WIZ_PRISMATIC_WALL);
    p = power_create();
    wizard_spell_immunity_setup(p);
    wizard_add_power(p, WIZ_SPELL_IMMUNITY);

    p = power_create();
    wizard_bigbys_crushing_hand_setup(p);
    wizard_add_power(p, WIZ_BIGBYS_CRUSHING_HAND);
    p = power_create();
    wizard_crystal_brittle_setup(p);
    wizard_add_power(p, WIZ_CRYSTAL_BRITTLE);
    p = power_create();
    wizard_level_drain_setup(p);
    wizard_add_power(p, WIZ_LEVEL_DRAIN);
    p = power_create();
    wizard_meteor_swarm_setup(p);
    wizard_add_power(p, WIZ_METEOR_SWARM);
    p = power_create();
    wizard_monster_summoning_vii_setup(p);
    wizard_add_power(p, WIZ_MONSTER_SUMMONING_VII);
    p = power_create();
    wizard_mordenkainens_disjunction_setup(p);
    wizard_add_power(p, WIZ_MORDENKAINENS_DISJUNCTION);
    p = power_create();
    wizard_power_word_kill_setup(p);
    wizard_add_power(p, WIZ_POWER_WORD_KILL);
    p = power_create();
    wizard_prismatic_sphere_setup(p);
    wizard_add_power(p, WIZ_PRISMATIC_SPHERE);
    p = power_create();
    wizard_time_stop_setup(p);
    wizard_add_power(p, WIZ_TIME_STOP);

    p = power_create();
    wizard_dome_of_invulnerability_setup(p);
    wizard_add_power(p, WIZ_DOME_OF_INVULNERABILITY);
    p = power_create();
    wizard_magical_plague_setup(p);
    wizard_add_power(p, WIZ_MAGICAL_PLAGUE);
    p = power_create();
    wizard_rift_setup(p);
    wizard_add_power(p, WIZ_RIFT);
    p = power_create();
    wizard_wall_of_ash_setup(p);
    wizard_add_power(p, WIZ_WALL_OF_ASH);

}
