#ifndef SOL_EVENT_H
#define SOL_EVENT_H

enum {
    SOL_PLAYER_UP,
    SOL_PLAYER_DOWN,
    SOL_PLAYER_LEFT,
    SOL_PLAYER_RIGHT,
    SOL_PLAYER_UL,
    SOL_PLAYER_UR,
    SOL_PLAYER_DL,
    SOL_PLAYER_DR,
    SOL_SCROLL_UP,
    SOL_SCROLL_DOWN,
    SOL_SCROLL_LEFT,
    SOL_SCROLL_RIGHT,
    SOL_SCROLL_UL,
    SOL_SCROLL_UR,
    SOL_SCROLL_DL,
    SOL_SCROLL_DR,
    SOL_ACTION,
    SOL_INVENTORY,
    SOL_CHARACTER,
};


#endif
