// This file is generated.
#include <stdlib.h>
#include "powers.h"
#include "wizard.h"

extern void wizard_armor_setup(power_t *p);
extern void wizard_burning_hands_setup(power_t *p);
extern void wizard_charm_person_setup(power_t *p);
extern void wizard_chill_touch_setup(power_t *p);
extern void wizard_color_spray_setup(power_t *p);
extern void wizard_enlarge_setup(power_t *p);
extern void wizard_gaze_reflection_setup(power_t *p);
extern void wizard_grease_setup(power_t *p);
extern void wizard_magic_missile_setup(power_t *p);
extern void wizard_shield_setup(power_t *p);
extern void wizard_shocking_grasp_setup(power_t *p);
extern void wizard_wall_of_fog_setup(power_t *p);

extern void wizard_blur_setup(power_t *p);
extern void wizard_detect_invisible_setup(power_t *p);
extern void wizard_flaming_sphere_setup(power_t *p);
extern void wizard_fog_cloud_setup(power_t *p);
extern void wizard_glitter_dust_setup(power_t *p);
extern void wizard_invisibility_setup(power_t *p);
extern void wizard_acid_arrow_setup(power_t *p);
extern void wizard_mirror_image_setup(power_t *p);
extern void wizard_protection_from_paralysis_setup(power_t *p);
extern void wizard_scare_setup(power_t *p);
extern void wizard_stinking_cloud_setup(power_t *p);
extern void wizard_strength_setup(power_t *p);
extern void wizard_web_setup(power_t *p);

extern void wizard_blink_setup(power_t *p);
extern void wizard_dispel_magic_setup(power_t *p);
extern void wizard_fireball_setup(power_t *p);
extern void wizard_flaming_arrow_setup(power_t *p);
extern void wizard_haste_setup(power_t *p);
extern void wizard_hold_person_setup(power_t *p);
extern void wizard_hold_undead_setup(power_t *p);
extern void wizard_lightning_bolt_setup(power_t *p);
extern void wizard_minute_meteors_setup(power_t *p);
extern void wizard_minor_malison_setup(power_t *p);
extern void wizard_protection_from_missiles_setup(power_t *p);
extern void wizard_slow_setup(power_t *p);
extern void wizard_spirit_armor_setup(power_t *p);
extern void wizard_vampiric_touch_setup(power_t *p);
extern void wizard_monster_summoning_i_setup(power_t *p);

extern void wizard_charm_monster_setup(power_t *p);
extern void wizard_confusion_setup(power_t *p);
extern void wizard_fear_setup(power_t *p);
extern void wizard_fire_shield_setup(power_t *p);
extern void wizard_ice_storm_setup(power_t *p);
extern void wizard_improved_invisibility_setup(power_t *p);
extern void wizard_m_globe_of_invulnerability_setup(power_t *p);
extern void wizard_minor_spell_turning_setup(power_t *p);
extern void wizard_otilukes_resilient_sphere_setup(power_t *p);
extern void wizard_psionic_dampener_setup(power_t *p);
extern void wizard_rainbow_pattern_setup(power_t *p);
extern void wizard_solid_fog_setup(power_t *p);
extern void wizard_spider_strand_setup(power_t *p);
extern void wizard_stone_skin_setup(power_t *p);
extern void wizard_pebble_to_boulder_setup(power_t *p);
extern void wizard_wall_of_fire_setup(power_t *p);
extern void wizard_wall_of_ice_setup(power_t *p);
extern void wizard_monster_summoning_ii_setup(power_t *p);
extern void wizard_evards_black_tentacles_setup(power_t *p);

extern void wizard_chaos_setup(power_t *p);
extern void wizard_cloud_kill_setup(power_t *p);
extern void wizard_cone_of_cold_setup(power_t *p);
extern void wizard_conjure_elemental_setup(power_t *p);
extern void wizard_dismissal_setup(power_t *p);
extern void wizard_dominate_setup(power_t *p);
extern void wizard_feeble_mind_setup(power_t *p);
extern void wizard_hold_monster_setup(power_t *p);
extern void wizard_lower_resistance_to_magic_setup(power_t *p);
extern void wizard_summon_shadow_setup(power_t *p);
extern void wizard_wall_of_force_setup(power_t *p);
extern void wizard_wall_of_stone_setup(power_t *p);
extern void wizard_monster_summoning_iii_setup(power_t *p);

extern void wizard_anti_magic_shell_setup(power_t *p);
extern void wizard_chain_lightning_setup(power_t *p);
extern void wizard_death_fog_setup(power_t *p);
extern void wizard_death_spell_setup(power_t *p);
extern void wizard_disintegrate_setup(power_t *p);
extern void wizard_globe_of_invulnerability_setup(power_t *p);
extern void wizard_improved_haste_setup(power_t *p);
extern void wizard_improved_slow_setup(power_t *p);
extern void wizard_monster_summoning_iv_setup(power_t *p);
extern void wizard_reincarnation_setup(power_t *p);
extern void wizard_stone_to_flesh_setup(power_t *p);
extern void wizard_flesh_to_stone_setup(power_t *p);
extern void wizard_tensers_transformation_setup(power_t *p);

extern void wizard_conjure_greater_elemental_setup(power_t *p);
extern void wizard_control_undead_setup(power_t *p);
extern void wizard_delayed_blast_fireball_setup(power_t *p);
extern void wizard_finger_of_death_setup(power_t *p);
extern void wizard_force_cage_setup(power_t *p);
extern void wizard_mass_invisibility_setup(power_t *p);
extern void wizard_monster_summoning_v_setup(power_t *p);
extern void wizard_mordenkainens_sword_setup(power_t *p);
extern void wizard_power_word_stun_setup(power_t *p);
extern void wizard_prismatic_spray_setup(power_t *p);
extern void wizard_spell_turning_setup(power_t *p);

extern void wizard_bigbys_clenched_fist_setup(power_t *p);
extern void wizard_incendiary_cloud_setup(power_t *p);
extern void wizard_mass_charm_setup(power_t *p);
extern void wizard_mind_blank_wizard_setup(power_t *p);
extern void wizard_monster_summoning_vi_setup(power_t *p);
extern void wizard_otilukes_telekinetic_sphere_setup(power_t *p);
extern void wizard_ottos_irresistible_dance_setup(power_t *p);
extern void wizard_power_word_blind_setup(power_t *p);
extern void wizard_prismatic_wall_setup(power_t *p);
extern void wizard_spell_immunity_setup(power_t *p);

extern void wizard_bigbys_crushing_hand_setup(power_t *p);
extern void wizard_crystal_brittle_setup(power_t *p);
extern void wizard_level_drain_setup(power_t *p);
extern void wizard_meteor_swarm_setup(power_t *p);
extern void wizard_monster_summoning_vii_setup(power_t *p);
extern void wizard_mordenkainens_disjunction_setup(power_t *p);
extern void wizard_power_word_kill_setup(power_t *p);
extern void wizard_prismatic_sphere_setup(power_t *p);
extern void wizard_time_stop_setup(power_t *p);

extern void wizard_dome_of_invulnerability_setup(power_t *p);
extern void wizard_magical_plague_setup(power_t *p);
extern void wizard_rift_setup(power_t *p);
extern void wizard_wall_of_ash_setup(power_t *p);


void wizard_setup_powers() {
    power_t *p;
    p = calloc(1, sizeof(power_t));
    wizard_armor_setup(p);
    wizard_add_power(1, p);
    p = calloc(1, sizeof(power_t));
    wizard_burning_hands_setup(p);
    wizard_add_power(1, p);
    p = calloc(1, sizeof(power_t));
    wizard_charm_person_setup(p);
    wizard_add_power(1, p);
    p = calloc(1, sizeof(power_t));
    wizard_chill_touch_setup(p);
    wizard_add_power(1, p);
    p = calloc(1, sizeof(power_t));
    wizard_color_spray_setup(p);
    wizard_add_power(1, p);
    p = calloc(1, sizeof(power_t));
    wizard_enlarge_setup(p);
    wizard_add_power(1, p);
    p = calloc(1, sizeof(power_t));
    wizard_gaze_reflection_setup(p);
    wizard_add_power(1, p);
    p = calloc(1, sizeof(power_t));
    wizard_grease_setup(p);
    wizard_add_power(1, p);
    p = calloc(1, sizeof(power_t));
    wizard_magic_missile_setup(p);
    wizard_add_power(1, p);
    p = calloc(1, sizeof(power_t));
    wizard_shield_setup(p);
    wizard_add_power(1, p);
    p = calloc(1, sizeof(power_t));
    wizard_shocking_grasp_setup(p);
    wizard_add_power(1, p);
    p = calloc(1, sizeof(power_t));
    wizard_wall_of_fog_setup(p);
    wizard_add_power(1, p);

    p = calloc(1, sizeof(power_t));
    wizard_blur_setup(p);
    wizard_add_power(2, p);
    p = calloc(1, sizeof(power_t));
    wizard_detect_invisible_setup(p);
    wizard_add_power(2, p);
    p = calloc(1, sizeof(power_t));
    wizard_flaming_sphere_setup(p);
    wizard_add_power(2, p);
    p = calloc(1, sizeof(power_t));
    wizard_fog_cloud_setup(p);
    wizard_add_power(2, p);
    p = calloc(1, sizeof(power_t));
    wizard_glitter_dust_setup(p);
    wizard_add_power(2, p);
    p = calloc(1, sizeof(power_t));
    wizard_invisibility_setup(p);
    wizard_add_power(2, p);
    p = calloc(1, sizeof(power_t));
    wizard_acid_arrow_setup(p);
    wizard_add_power(2, p);
    p = calloc(1, sizeof(power_t));
    wizard_mirror_image_setup(p);
    wizard_add_power(2, p);
    p = calloc(1, sizeof(power_t));
    wizard_protection_from_paralysis_setup(p);
    wizard_add_power(2, p);
    p = calloc(1, sizeof(power_t));
    wizard_scare_setup(p);
    wizard_add_power(2, p);
    p = calloc(1, sizeof(power_t));
    wizard_stinking_cloud_setup(p);
    wizard_add_power(2, p);
    p = calloc(1, sizeof(power_t));
    wizard_strength_setup(p);
    wizard_add_power(2, p);
    p = calloc(1, sizeof(power_t));
    wizard_web_setup(p);
    wizard_add_power(2, p);

    p = calloc(1, sizeof(power_t));
    wizard_blink_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_dispel_magic_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_fireball_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_flaming_arrow_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_haste_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_hold_person_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_hold_undead_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_lightning_bolt_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_minute_meteors_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_minor_malison_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_protection_from_missiles_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_slow_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_spirit_armor_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_vampiric_touch_setup(p);
    wizard_add_power(3, p);
    p = calloc(1, sizeof(power_t));
    wizard_monster_summoning_i_setup(p);
    wizard_add_power(3, p);

    p = calloc(1, sizeof(power_t));
    wizard_charm_monster_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_confusion_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_fear_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_fire_shield_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_ice_storm_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_improved_invisibility_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_m_globe_of_invulnerability_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_minor_spell_turning_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_otilukes_resilient_sphere_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_psionic_dampener_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_rainbow_pattern_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_solid_fog_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_spider_strand_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_stone_skin_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_pebble_to_boulder_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_wall_of_fire_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_wall_of_ice_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_monster_summoning_ii_setup(p);
    wizard_add_power(4, p);
    p = calloc(1, sizeof(power_t));
    wizard_evards_black_tentacles_setup(p);
    wizard_add_power(4, p);

    p = calloc(1, sizeof(power_t));
    wizard_chaos_setup(p);
    wizard_add_power(5, p);
    p = calloc(1, sizeof(power_t));
    wizard_cloud_kill_setup(p);
    wizard_add_power(5, p);
    p = calloc(1, sizeof(power_t));
    wizard_cone_of_cold_setup(p);
    wizard_add_power(5, p);
    p = calloc(1, sizeof(power_t));
    wizard_conjure_elemental_setup(p);
    wizard_add_power(5, p);
    p = calloc(1, sizeof(power_t));
    wizard_dismissal_setup(p);
    wizard_add_power(5, p);
    p = calloc(1, sizeof(power_t));
    wizard_dominate_setup(p);
    wizard_add_power(5, p);
    p = calloc(1, sizeof(power_t));
    wizard_feeble_mind_setup(p);
    wizard_add_power(5, p);
    p = calloc(1, sizeof(power_t));
    wizard_hold_monster_setup(p);
    wizard_add_power(5, p);
    p = calloc(1, sizeof(power_t));
    wizard_lower_resistance_to_magic_setup(p);
    wizard_add_power(5, p);
    p = calloc(1, sizeof(power_t));
    wizard_summon_shadow_setup(p);
    wizard_add_power(5, p);
    p = calloc(1, sizeof(power_t));
    wizard_wall_of_force_setup(p);
    wizard_add_power(5, p);
    p = calloc(1, sizeof(power_t));
    wizard_wall_of_stone_setup(p);
    wizard_add_power(5, p);
    p = calloc(1, sizeof(power_t));
    wizard_monster_summoning_iii_setup(p);
    wizard_add_power(5, p);

    p = calloc(1, sizeof(power_t));
    wizard_anti_magic_shell_setup(p);
    wizard_add_power(6, p);
    p = calloc(1, sizeof(power_t));
    wizard_chain_lightning_setup(p);
    wizard_add_power(6, p);
    p = calloc(1, sizeof(power_t));
    wizard_death_fog_setup(p);
    wizard_add_power(6, p);
    p = calloc(1, sizeof(power_t));
    wizard_death_spell_setup(p);
    wizard_add_power(6, p);
    p = calloc(1, sizeof(power_t));
    wizard_disintegrate_setup(p);
    wizard_add_power(6, p);
    p = calloc(1, sizeof(power_t));
    wizard_globe_of_invulnerability_setup(p);
    wizard_add_power(6, p);
    p = calloc(1, sizeof(power_t));
    wizard_improved_haste_setup(p);
    wizard_add_power(6, p);
    p = calloc(1, sizeof(power_t));
    wizard_improved_slow_setup(p);
    wizard_add_power(6, p);
    p = calloc(1, sizeof(power_t));
    wizard_monster_summoning_iv_setup(p);
    wizard_add_power(6, p);
    p = calloc(1, sizeof(power_t));
    wizard_reincarnation_setup(p);
    wizard_add_power(6, p);
    p = calloc(1, sizeof(power_t));
    wizard_stone_to_flesh_setup(p);
    wizard_add_power(6, p);
    p = calloc(1, sizeof(power_t));
    wizard_flesh_to_stone_setup(p);
    wizard_add_power(6, p);
    p = calloc(1, sizeof(power_t));
    wizard_tensers_transformation_setup(p);
    wizard_add_power(6, p);

    p = calloc(1, sizeof(power_t));
    wizard_conjure_greater_elemental_setup(p);
    wizard_add_power(7, p);
    p = calloc(1, sizeof(power_t));
    wizard_control_undead_setup(p);
    wizard_add_power(7, p);
    p = calloc(1, sizeof(power_t));
    wizard_delayed_blast_fireball_setup(p);
    wizard_add_power(7, p);
    p = calloc(1, sizeof(power_t));
    wizard_finger_of_death_setup(p);
    wizard_add_power(7, p);
    p = calloc(1, sizeof(power_t));
    wizard_force_cage_setup(p);
    wizard_add_power(7, p);
    p = calloc(1, sizeof(power_t));
    wizard_mass_invisibility_setup(p);
    wizard_add_power(7, p);
    p = calloc(1, sizeof(power_t));
    wizard_monster_summoning_v_setup(p);
    wizard_add_power(7, p);
    p = calloc(1, sizeof(power_t));
    wizard_mordenkainens_sword_setup(p);
    wizard_add_power(7, p);
    p = calloc(1, sizeof(power_t));
    wizard_power_word_stun_setup(p);
    wizard_add_power(7, p);
    p = calloc(1, sizeof(power_t));
    wizard_prismatic_spray_setup(p);
    wizard_add_power(7, p);
    p = calloc(1, sizeof(power_t));
    wizard_spell_turning_setup(p);
    wizard_add_power(7, p);

    p = calloc(1, sizeof(power_t));
    wizard_bigbys_clenched_fist_setup(p);
    wizard_add_power(8, p);
    p = calloc(1, sizeof(power_t));
    wizard_incendiary_cloud_setup(p);
    wizard_add_power(8, p);
    p = calloc(1, sizeof(power_t));
    wizard_mass_charm_setup(p);
    wizard_add_power(8, p);
    p = calloc(1, sizeof(power_t));
    wizard_mind_blank_wizard_setup(p);
    wizard_add_power(8, p);
    p = calloc(1, sizeof(power_t));
    wizard_monster_summoning_vi_setup(p);
    wizard_add_power(8, p);
    p = calloc(1, sizeof(power_t));
    wizard_otilukes_telekinetic_sphere_setup(p);
    wizard_add_power(8, p);
    p = calloc(1, sizeof(power_t));
    wizard_ottos_irresistible_dance_setup(p);
    wizard_add_power(8, p);
    p = calloc(1, sizeof(power_t));
    wizard_power_word_blind_setup(p);
    wizard_add_power(8, p);
    p = calloc(1, sizeof(power_t));
    wizard_prismatic_wall_setup(p);
    wizard_add_power(8, p);
    p = calloc(1, sizeof(power_t));
    wizard_spell_immunity_setup(p);
    wizard_add_power(8, p);

    p = calloc(1, sizeof(power_t));
    wizard_bigbys_crushing_hand_setup(p);
    wizard_add_power(9, p);
    p = calloc(1, sizeof(power_t));
    wizard_crystal_brittle_setup(p);
    wizard_add_power(9, p);
    p = calloc(1, sizeof(power_t));
    wizard_level_drain_setup(p);
    wizard_add_power(9, p);
    p = calloc(1, sizeof(power_t));
    wizard_meteor_swarm_setup(p);
    wizard_add_power(9, p);
    p = calloc(1, sizeof(power_t));
    wizard_monster_summoning_vii_setup(p);
    wizard_add_power(9, p);
    p = calloc(1, sizeof(power_t));
    wizard_mordenkainens_disjunction_setup(p);
    wizard_add_power(9, p);
    p = calloc(1, sizeof(power_t));
    wizard_power_word_kill_setup(p);
    wizard_add_power(9, p);
    p = calloc(1, sizeof(power_t));
    wizard_prismatic_sphere_setup(p);
    wizard_add_power(9, p);
    p = calloc(1, sizeof(power_t));
    wizard_time_stop_setup(p);
    wizard_add_power(9, p);

    p = calloc(1, sizeof(power_t));
    wizard_dome_of_invulnerability_setup(p);
    wizard_add_power(10, p);
    p = calloc(1, sizeof(power_t));
    wizard_magical_plague_setup(p);
    wizard_add_power(10, p);
    p = calloc(1, sizeof(power_t));
    wizard_rift_setup(p);
    wizard_add_power(10, p);
    p = calloc(1, sizeof(power_t));
    wizard_wall_of_ash_setup(p);
    wizard_add_power(10, p);

}
